# cargo-about configuration. Generates THIRD_PARTY_NOTICES.md from the lockfile:
#   cargo about generate about.hbs --all-features > THIRD_PARTY_NOTICES.md
# Build/dev dependencies are excluded: only code that ships in the published
# crates needs attribution. If a dependency license is rejected, add it here
# (or add a [[licenses.clarify]] for crates that declare a license only by file).

accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "Unicode-3.0",
    "Unicode-DFS-2016",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
filter-noassertion = true
