//! Clipboard events for async processing.
//!
//! The IronRDP [`CliprdrBackend`](ironrdp_cliprdr::backend::CliprdrBackend) trait methods
//! are called synchronously. This module provides event types that allow queueing
//! operations for asynchronous processing.

use ironrdp_cliprdr::pdu::{
    ClipboardFormat as RdpClipboardFormat, ClipboardFormatId, ClipboardGeneralCapabilityFlags, FileContentsFlags,
    FileContentsRequest, FileContentsResponse, FileDescriptor, FormatDataRequest, FormatDataResponse, LockDataId,
};
use std::collections::VecDeque;
use std::sync::{Arc, Mutex, MutexGuard, PoisonError};
use std::task::{Poll, Waker};

/// Metadata for one file in a remote `FileGroupDescriptorW` list.
///
/// Owned copy of the fields a consumer needs to present the remote files
/// locally (e.g. build `file://` URIs backed by a FUSE mount) without holding a
/// borrow into the IronRDP PDU across the async boundary.
#[derive(Debug, Clone)]
pub struct RemoteFileMetadata {
    /// File name (leaf, without directory separators).
    pub name: String,
    /// File size in bytes, if the remote provided it.
    pub size: Option<u64>,
    /// Relative directory path within the copied collection (`\`-separated),
    /// or `None` for a root-level file.
    pub relative_path: Option<String>,
}

/// Events generated by the clipboard backend for async processing.
#[derive(Debug, Clone)]
pub enum ClipboardEvent {
    /// Backend is ready (channel initialized)
    Ready,

    /// Request to send format list
    RequestFormatList,

    /// Negotiated capabilities received
    NegotiatedCapabilities(ClipboardGeneralCapabilityFlags),

    /// Remote clipboard content changed (remote copy)
    RemoteCopy {
        /// Available formats from remote
        formats: Vec<RdpClipboardFormat>,
    },

    /// Remote requests format data
    FormatDataRequest {
        /// The requested format ID
        format_id: ClipboardFormatId,
    },

    /// Remote sent format data response
    FormatDataResponse {
        /// The format data (owned copy)
        data: Vec<u8>,
        /// Whether this is an error response
        is_error: bool,
    },

    /// Remote requests file contents
    FileContentsRequest {
        /// Stream ID for correlation
        stream_id: u32,
        /// File index (lindex). Per [MS-RDPECLIP] 2.2.5.3 this is a signed
        /// 32-bit integer; negative values are rejected during decode.
        index: i32,
        /// Byte offset
        position: u64,
        /// Requested size
        size: u32,
        /// Whether this is a size request (vs data request)
        is_size_request: bool,
    },

    /// Remote sent file contents response
    FileContentsResponse {
        /// Stream ID for correlation
        stream_id: u32,
        /// File data (owned copy)
        data: Vec<u8>,
        /// Whether this is an error response
        is_error: bool,
    },

    /// Remote sent a file list ([MS-RDPECLIP] 2.2.5.2 Packed File List) in
    /// response to a paste request for `FileGroupDescriptorW`. Carries the file
    /// metadata and the clipDataId of the auto-created lock, for use in later
    /// file-contents requests against the locked snapshot.
    RemoteFileList {
        /// File metadata from the remote.
        files: Vec<RemoteFileMetadata>,
        /// clipDataId of the lock created when the format list arrived, or
        /// `None` if `CAN_LOCK_CLIPDATA` was not negotiated.
        clip_data_id: Option<u32>,
    },

    /// Clipboard lock request
    Lock {
        /// Data ID to lock
        data_id: u32,
    },

    /// Clipboard unlock request
    Unlock {
        /// Data ID to unlock
        data_id: u32,
    },
}

impl ClipboardEvent {
    /// Create a RemoteCopy event from RDP format list
    pub fn remote_copy(formats: &[RdpClipboardFormat]) -> Self {
        Self::RemoteCopy {
            formats: formats.to_vec(),
        }
    }

    /// Create a FormatDataRequest event
    pub fn format_data_request(request: &FormatDataRequest) -> Self {
        Self::FormatDataRequest {
            format_id: request.format,
        }
    }

    /// Create a FormatDataResponse event
    pub fn format_data_response(response: &FormatDataResponse<'_>) -> Self {
        Self::FormatDataResponse {
            data: response.data().to_vec(),
            is_error: response.is_error(),
        }
    }

    /// Create a FileContentsRequest event
    pub fn file_contents_request(request: &FileContentsRequest) -> Self {
        Self::FileContentsRequest {
            stream_id: request.stream_id,
            index: request.index,
            position: request.position,
            size: request.requested_size,
            is_size_request: request.flags.contains(FileContentsFlags::SIZE),
        }
    }

    /// Create a FileContentsResponse event
    pub fn file_contents_response(response: &FileContentsResponse<'_>) -> Self {
        // Note: FileContentsResponse doesn't expose is_error publicly,
        // so we infer error state from empty data
        Self::FileContentsResponse {
            stream_id: response.stream_id(),
            data: response.data().to_vec(),
            is_error: response.data().is_empty(),
        }
    }

    /// Create a RemoteFileList event from a remote file descriptor list.
    pub fn remote_file_list(files: &[FileDescriptor], clip_data_id: Option<u32>) -> Self {
        Self::RemoteFileList {
            files: files
                .iter()
                .map(|f| RemoteFileMetadata {
                    name: f.name.clone(),
                    size: f.file_size,
                    relative_path: f.relative_path.clone(),
                })
                .collect(),
            clip_data_id,
        }
    }

    /// Create a Lock event
    pub fn lock(data_id: LockDataId) -> Self {
        Self::Lock { data_id: data_id.0 }
    }

    /// Create an Unlock event
    pub fn unlock(data_id: LockDataId) -> Self {
        Self::Unlock { data_id: data_id.0 }
    }
}

#[derive(Debug, Default)]
struct EventQueue {
    events: VecDeque<ClipboardEvent>,
    /// Tasks parked in [`ClipboardEventReceiver::recv`].
    waiters: Vec<Waker>,
}

#[derive(Debug, Default)]
struct SharedQueue(Mutex<EventQueue>);

impl SharedQueue {
    // The lock only guards a push or a pop, so a poisoned queue is still usable.
    fn lock(&self) -> MutexGuard<'_, EventQueue> {
        self.0.lock().unwrap_or_else(PoisonError::into_inner)
    }
}

/// Sender side of the clipboard event channel.
///
/// The IronRDP backend calls in synchronously, so sending only pushes onto a
/// shared queue and wakes any task waiting in [`ClipboardEventReceiver::recv`].
#[derive(Debug, Clone)]
pub struct ClipboardEventSender {
    queue: Arc<SharedQueue>,
}

impl ClipboardEventSender {
    /// Create a new event sender
    pub fn new() -> Self {
        Self {
            queue: Arc::new(SharedQueue::default()),
        }
    }

    /// Send an event (non-blocking, queues for later processing)
    pub fn send(&self, event: ClipboardEvent) {
        let waiters = {
            let mut queue = self.queue.lock();
            queue.events.push_back(event);
            std::mem::take(&mut queue.waiters)
        };
        for waiter in waiters {
            waiter.wake();
        }
    }

    /// Create a receiver that shares the same queue
    pub fn subscribe(&self) -> ClipboardEventReceiver {
        ClipboardEventReceiver {
            queue: Arc::clone(&self.queue),
        }
    }
}

impl Default for ClipboardEventSender {
    fn default() -> Self {
        Self::new()
    }
}

/// Receiver side of the clipboard event channel.
#[derive(Debug, Clone)]
pub struct ClipboardEventReceiver {
    queue: Arc<SharedQueue>,
}

impl ClipboardEventReceiver {
    /// Try to receive the next event (non-blocking)
    pub fn try_recv(&self) -> Option<ClipboardEvent> {
        self.queue.lock().events.pop_front()
    }

    /// Wait for the next event.
    ///
    /// Lets an async consumer sleep until the backend queues something instead
    /// of polling [`try_recv`](Self::try_recv) on a timer.
    pub async fn recv(&self) -> ClipboardEvent {
        std::future::poll_fn(|cx| {
            let mut queue = self.queue.lock();
            if let Some(event) = queue.events.pop_front() {
                return Poll::Ready(event);
            }
            if !queue.waiters.iter().any(|w| w.will_wake(cx.waker())) {
                queue.waiters.push(cx.waker().clone());
            }
            Poll::Pending
        })
        .await
    }

    /// Drain all pending events
    pub fn drain(&self) -> Vec<ClipboardEvent> {
        self.queue.lock().events.drain(..).collect()
    }

    /// Check if there are pending events
    pub fn has_pending(&self) -> bool {
        !self.queue.lock().events.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn block_on<F: std::future::Future>(future: F) -> F::Output {
        struct ThreadWaker(std::thread::Thread);
        impl std::task::Wake for ThreadWaker {
            fn wake(self: Arc<Self>) {
                self.0.unpark();
            }
        }
        let waker = Waker::from(Arc::new(ThreadWaker(std::thread::current())));
        let mut cx = std::task::Context::from_waker(&waker);
        let mut future = std::pin::pin!(future);
        loop {
            if let Poll::Ready(out) = future.as_mut().poll(&mut cx) {
                return out;
            }
            std::thread::park();
        }
    }

    #[test]
    fn recv_wakes_when_another_thread_sends() {
        let sender = ClipboardEventSender::new();
        let receiver = sender.subscribe();
        let producer = std::thread::spawn(move || {
            std::thread::sleep(std::time::Duration::from_millis(20));
            sender.send(ClipboardEvent::Ready);
        });
        assert!(matches!(block_on(receiver.recv()), ClipboardEvent::Ready));
        producer.join().unwrap();
    }

    #[test]
    fn concurrent_sends_are_all_queued() {
        let sender = ClipboardEventSender::new();
        let receiver = sender.subscribe();
        let threads: Vec<_> = (0..8)
            .map(|_| {
                let sender = sender.clone();
                std::thread::spawn(move || {
                    for _ in 0..500 {
                        sender.send(ClipboardEvent::RequestFormatList);
                    }
                })
            })
            .collect();
        let mut received = 0;
        while received < 8 * 500 {
            if receiver.try_recv().is_some() {
                received += 1;
            }
        }
        for thread in threads {
            thread.join().unwrap();
        }
        assert!(receiver.try_recv().is_none());
    }

    #[test]
    fn test_event_channel() {
        let sender = ClipboardEventSender::new();
        let receiver = sender.subscribe();

        sender.send(ClipboardEvent::Ready);
        sender.send(ClipboardEvent::RequestFormatList);

        assert!(receiver.has_pending());

        let events = receiver.drain();
        assert_eq!(events.len(), 2);
        assert!(matches!(events[0], ClipboardEvent::Ready));
        assert!(matches!(events[1], ClipboardEvent::RequestFormatList));

        assert!(!receiver.has_pending());
    }

    #[test]
    fn test_try_recv() {
        let sender = ClipboardEventSender::new();
        let receiver = sender.subscribe();

        assert!(receiver.try_recv().is_none());

        sender.send(ClipboardEvent::Ready);

        let event = receiver.try_recv();
        assert!(matches!(event, Some(ClipboardEvent::Ready)));
        assert!(receiver.try_recv().is_none());
    }
}
